# JxMVC — Demo site configuration
jxmvc.controllers.package = jxmvc.controllers
jxmvc.services.package    = jxmvc.services
jxmvc.profile             = prod
jxmvc.log.level           = INFO
jxmvc.async.threads       = 8

# Pool deshabilitado — demo site sin BD
jxmvc.pool.enabled        = false

jxmvc.security.frame-options = SAMEORIGIN
jxmvc.security.hsts          = true
